# Generated by Django 4.0.7 on 2023-01-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('tramite', models.CharField(choices=[('Matricula', 'Matricula'), ('Traspaso', 'Traspaso'), ('Traslado_matricula', 'Traslado_matricula'), ('Radicado_matricula', 'Radicado_matricula'), ('Cambio_coor', 'Cambio_coor'), ('Cambio_servicio', 'Cambio_servicio'), ('Regresar_motor', 'Regresar_motor'), ('Regresar_chasis', 'Regresar_chasis'), ('Transformacion', 'Transformacion'), ('Duplicado_matricula', 'Duplicado_matricula'), ('Inscripcion', 'Inscripcion'), ('Levantaprenda', 'Levantaprenda'), ('Cancelacion_matricula', 'Cancelacion_matricula'), ('Cambio_placas', 'Cambio_placas'), ('Duplicado_placas', 'Duplicado_placas'), ('Rematricula', 'Rematricula'), ('Cambio_carroceria', 'Cambio_carroceria'), ('Otros', 'Otros')], max_length=21)),
                ('clase_de_vehiculo', models.CharField(choices=[('Automovil', 'Automovil'), ('Bus', 'Bus'), ('Buseta', 'Buseta'), ('Camion', 'Camion'), ('Camioneta', 'Camioneta'), ('Campero', 'Campero'), ('Microbus', 'Microbus'), ('Tractocamion', 'Tractocamion'), ('Motocicleta', 'Motocicleta'), ('Motocarro', 'Motocarro'), ('Mototriciclo', 'Mototriciclo'), ('Cuatrimoto', 'Cuatrimoto'), ('Volqueta', 'Volqueta'), ('Otro', 'Otro')], max_length=14)),
                ('marca', models.CharField(max_length=30)),
                ('linea', models.CharField(max_length=50)),
                ('combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Gas', 'Gas'), ('Mixto', 'Mixto'), ('Electrico', 'Electrico'), ('Hidrogen', 'Hidrogen'), ('Etanol', 'Etanol'), ('Biodiese', 'Biodiese')], max_length=14)),
                ('color', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('cilindraje', models.CharField(max_length=30)),
                ('capacidad', models.CharField(max_length=4)),
                ('blindaje', models.BooleanField()),
                ('desmonteblind', models.BooleanField()),
                ('potencia', models.IntegerField()),
                ('codigo_carroceria', models.CharField(max_length=30)),
                ('tipo_carroceria', models.CharField(max_length=15)),
                ('No_motor', models.CharField(max_length=30)),
                ('No_chasis', models.CharField(max_length=30)),
                ('No_serie', models.CharField(max_length=30)),
                ('Vin', models.IntegerField()),
                ('imp_o_rem', models.CharField(choices=[('Manif', 'Manif'), ('Dec', 'Dec'), ('Acta', 'Acta'), ('Entidad', 'Entidad'), ('Lugar', 'Lugar'), ('Codigo', 'Codigo')], max_length=14)),
                ('documento', models.IntegerField()),
                ('fecha', models.DateField()),
                ('tipo_servicio', models.CharField(choices=[('particular', 'particular'), ('publico', 'publico'), ('diplomatico', 'diplomatico'), ('oficial', 'oficial'), ('especial', 'especial'), ('otros', 'otros')], max_length=14)),
                ('nombre_empresa', models.CharField(max_length=30)),
                ('NIT', models.IntegerField()),
                ('datos_alerta', models.CharField(choices=[('hurto', 'hurto'), ('lim', 'lim'), ('embargo', 'embargo'), ('otro', 'otro'), ('A_favor', 'A_favor')], max_length=14)),
                ('nombres_vendedor', models.CharField(max_length=30)),
                ('apellido1_vendedor', models.CharField(max_length=30)),
                ('apellido2_vendedor', models.CharField(max_length=30)),
                ('id_vendedor', models.CharField(choices=[('c', 'C.C'), ('n', 'NIT'), ('x', 'N.N'), ('p', 'Pasaporte'), ('e', 'C.extranjero'), ('t', 'T.identidad'), ('u', 'NUIP'), ('d', 'C.diplomatico')], max_length=14)),
                ('documento_vendedor', models.IntegerField()),
                ('direccion_vendedor', models.CharField(max_length=100)),
                ('ciudad_vendedor', models.CharField(max_length=30)),
                ('telefono_vendedor', models.CharField(max_length=10)),
                ('firma_vendedor', models.CharField(max_length=30)),
                ('nombres_comprador', models.CharField(max_length=30)),
                ('apellido1_comprador', models.CharField(max_length=30)),
                ('apellido2_comprador', models.CharField(max_length=30)),
                ('id_comprador', models.CharField(choices=[('c', 'C.C'), ('n', 'NIT'), ('x', 'N.N'), ('p', 'Pasaporte'), ('e', 'C.extranjero'), ('t', 'T.identidad'), ('u', 'NUIP'), ('d', 'C.diplomatico')], max_length=14)),
                ('documento_comprador', models.IntegerField()),
                ('direccion_comprador', models.CharField(max_length=100)),
                ('ciudad_comprador', models.CharField(max_length=30)),
                ('telefono_comprador', models.CharField(max_length=10)),
                ('firma_comprador', models.CharField(max_length=30)),
            ],
        ),
    ]
